[package]
name = "git-rename-stash"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
authors = ["Henry Till <henrytill@gmail.com>"]
repository = "https://github.com/henrytill/git-rename-stash"

[dependencies]
git2 = "0.20.0"
